package shov.studio.pkh.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.artifacts.ProjectDependency
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

class LocalDependencyGraphPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        val taskProvider = project.tasks.register("generateModuleDependencyGraph", GenerateModuleDependencyGraphTask::class.java) {
            group = "documentation"
            description = "Generates a Mermaid graph of internal Gradle module dependencies."
            outputFile.set(project.rootProject.layout.projectDirectory.file("docs/architecture/module-dependency-graph.mmd"))
        }

        project.gradle.projectsEvaluated {
            val moduleProjects = project.rootProject.subprojects
                .filter { it.buildFile.isFile }

            val modules = moduleProjects
                .map { it.path }
                .sortedWith(modulePathComparator())
            val modulePathSet = modules.toSet()

            val edgesByModules = sortedMapOf<Pair<String, String>, MutableSet<String>>(
                compareBy<Pair<String, String>> { it.first }.thenBy { it.second }
            )

            moduleProjects.forEach { module ->
                module.configurations.forEach { configuration ->
                    configuration.dependencies
                        .withType(ProjectDependency::class.java)
                        .forEach { dependency ->
                            val dependentModule = module.path
                            val dependencyModule = dependency.path
                            if (dependentModule != dependencyModule && dependencyModule in modulePathSet) {
                                edgesByModules
                                    .getOrPut(dependentModule to dependencyModule) { sortedSetOf() }
                                    .add(configuration.name)
                            }
                        }
                }
            }

            val edges = edgesByModules.map { (edge, configurations) ->
                listOf(edge.first, edge.second, configurations.joinToString(", ")).joinToString(EDGE_SEPARATOR)
            }

            taskProvider.configure {
                modulePaths.set(modules)
                dependencyEdges.set(edges)
            }
        }
    }
}

abstract class GenerateModuleDependencyGraphTask : DefaultTask() {
    @get:Input
    abstract val modulePaths: ListProperty<String>

    @get:Input
    abstract val dependencyEdges: ListProperty<String>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val content = buildString {
            appendLine("%% Generated by :generateModuleDependencyGraph.")
            appendLine("%% Internal Gradle project dependencies only; external dependencies are intentionally omitted.")
            appendLine("flowchart LR")

            ModuleGroup.values().forEach { group ->
                val groupModules = modulePaths.get().filter { moduleGroup(it) == group }
                if (groupModules.isNotEmpty()) {
                    appendLine("    subgraph ${group.id}[\"${group.title}\"]")
                    appendLine("        direction TB")
                    groupModules.forEach { modulePath ->
                        appendLine("        ${nodeId(modulePath)}[\"${escapeLabel(modulePath)}\"]")
                    }
                    appendLine("    end")
                    appendLine()
                }
            }

            dependencyEdges.get().forEach { encodedEdge ->
                val (dependentModule, dependencyModule, label) = encodedEdge.split(EDGE_SEPARATOR, limit = 3)
                appendLine("    ${nodeId(dependentModule)} -->|\"${escapeLabel(label)}\"| ${nodeId(dependencyModule)}")
            }
        }

        val targetFile = outputFile.get().asFile
        targetFile.parentFile.mkdirs()
        targetFile.writeText(content)
    }

    private fun nodeId(modulePath: String): String =
        "module_" + modulePath
            .trimStart(':')
            .ifEmpty { "root" }
            .replace(Regex("[^A-Za-z0-9_]"), "_")

    private fun escapeLabel(value: String): String =
        value.replace("\\", "\\\\").replace("\"", "\\\"")
}

private const val EDGE_SEPARATOR = "\u001F"

private fun modulePathComparator(): Comparator<String> =
    compareBy<String> { it.count { char -> char == ':' } }.thenBy { it }

private enum class ModuleGroup(
    val id: String,
    val title: String,
) {
    EntryPoints("entry_points", "Entrypoints / Shared"),
    Feature("feature_modules", "Feature modules"),
    Domain("domain_modules", "Domain modules"),
    DataApi("data_api_modules", "Data API modules"),
    DataImpl("data_impl_modules", "Data implementation modules"),
    DataContract("data_contract_modules", "Data contract modules"),
    Backend("backend_modules", "Backend modules"),
    Other("other_modules", "Other modules"),
}

private fun moduleGroup(modulePath: String): ModuleGroup =
    when {
        modulePath == ":server" || modulePath.startsWith(":server:") -> ModuleGroup.Backend
        modulePath == ":shared" || modulePath == ":composeApp" -> ModuleGroup.EntryPoints
        modulePath.startsWith(":feature:") -> ModuleGroup.Feature
        modulePath.startsWith(":domain:") -> ModuleGroup.Domain
        modulePath.startsWith(":data:") && modulePath.endsWith(":api") -> ModuleGroup.DataApi
        modulePath.startsWith(":data:") && modulePath.endsWith(":impl") -> ModuleGroup.DataImpl
        modulePath.startsWith(":data:") && modulePath.endsWith(":contract") -> ModuleGroup.DataContract
        else -> ModuleGroup.Other
    }
